### ISSUE TITLE
too sad ~~~

### ISSUE THREAD

**Issue by yuelao025** [GUI/lua-resty-mail#1]
2017/08/12 16:08:29 [error] 34930#0: *36482 attempt to send data on a closed socket: u:000000000EAB9370, c:0000000000000000, ft:8 eof:0, client: 127.0.0.1, server: _, request: "GET /lib/mail_test HTTP/1.1", host: "localhost"

**Comment by yuelao025** [comment]
whatever smtp.com   or smtp.qq.com

**Comment by yuelao025** [comment]
whatever smtp.163.com or smtp.qq.com

**Comment by GUI** [comment]
Can you share an example of what code is triggering this error?

**Comment by GUI** [comment]
Going to go ahead and close this issue, but let me know if you have additional information about this error.

**Comment by h3ge** [comment]
Had the same issue.
smtp.lua trys to call method "sock:settimeouts", which is not available under my setup.
`smtp.lua:144: attempt to call method 'settimeouts' (a nil value)`

I changed the method call to 
`sock:settimeout(options["timeout_send"])`

Now everything is working, great work btw!

My setup:
I'm using ubuntu 16.04 and the nginx-extras package

**Comment by edubart** [comment]
The error "attempt to send data on a closed socket" is related to #2

**Comment by GUI** [comment]
@h3ge: FYI, I've released v1.0.1 which includes compatibility with older ngx_lua versions that lack `settimeouts` support.
