### ISSUE TITLE
/usr/local/openresty/site/lualib/resty/mail/smtp.lua:155: closed

### ISSUE THREAD

**Issue by sahuguet** [GUI/lua-resty-mail#3]
I tried the code sample against GMail using `resty` command-line tool and I get this error:
/usr/local/openresty/site/lualib/resty/mail/smtp.lua:155: closed

Same error when I try from within nginx.

I checked my GMail config (server, port, credentials) against some Python code and it works fine.

**Comment by GUI** [comment]
@sahuguet: Sorry for the delay. Can you provide more details on how you're trying to connect (eg, what port, whether starttls is being used, etc)?

Or as another test, could you try creating this `test-mail.lua` file: https://gist.github.com/GUI/4ec6e695b400d8128b5708c2acf4e8fa, fill in your own Gmail `username` and `password`, and then try running `resty test-mail.lua`? I was just able to successfully run this test, so I'm curious if you'd see the same `closed` error with this example.

**Comment by GUI** [comment]
I'm going to close this, but give a shout if this is still an issue with the latest version and you can provide more debug details.
